### ISSUE TITLE
ModuleNotFoundError: No module named 'torch'

### ISSUE THREAD

**Issue by filipruisl** [FahimF/sd-gui#2]
I've been able to go through the whole process without issues, but can't launch the script. I've checked and pytorch with other dependencies were installed without issues, but for some reason it can't be accessed it seems. Do you maybe know what I'm doing wrong? Thank you <3 

```
(ml) phylyp@Phylyps-MacBook-Pro sd-gui % python gui.py
Traceback (most recent call last):
  File "/Users/phylyp/sd-gui/sd-gui/gui.py", line 2, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
(ml) phylyp@Phylyps-MacBook-Pro sd-gui % 
```

**Comment by FahimF** [comment]
Closing this since I already responded on Reddit 😄
